config/routes.rb
Semaphore::Application.routes.draw do

  resources :categories
  resources :events

  root :to => 'events#index'

end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name
  field :slug
  key :name
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :events
  before_save :generate_slug
  protected
  def generate_slug
    self.slug = name
  end
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::MultiParameterAttributes

  field :title
  field :description
  field :starts_at, :type => DateTime
  field :ends_at, :type => DateTime
  field :source
  key :title
  
  belongs_to :category
  validates_presence_of :title, :description
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :ok }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/categories/_form.html.slim
= form_for(@category) do |f|

  - if @category.errors.any?
    #error_explanation
      h2 = pluralize(@category.errors.count, "error")
      | prohibited this category from being saved:
      ul
      - @category.errors.full_messages.each do |msg|
        li = msg

  .field
    = f.label :name
    br
    = f.text_field :name
  
  .actions
    = f.submit

app/views/categories/edit.html.slim
h1 Editing category

= render 'form'

= link_to 'Show', @category
|  | 
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  tr
    th Name
    th
    th
    th

  - @categories.each do |category|
    tr
      td = category.name
      td = link_to 'Show', category
      td = link_to 'Edit', edit_category_path(category)
      td = link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/new.html.slim
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.slim
p#notice = notice

h1 = @category.name

ul
  - for event in @category.events
    li = event.title

= link_to 'Edit', edit_category_path(@category)
|  | 
= link_to 'Back', categories_path

app/views/events/_form.html.slim
= form_for(@event) do |f|

  - if @event.errors.any?
    #error_explanation
      h2 = pluralize(@event.errors.count, "error")
      | prohibited this event from being saved:
      ul
      - @event.errors.full_messages.each do |msg|
        li = msg

  .field
    = f.label :title
    br
    = f.text_field :title
    
  .field
    = f.label :description
    br
    = f.text_area :description

  .field
    = f.label :category_id
    br
    = f.collection_select :category_id, Category.all, :id, :name
  
  .field
    = f.label :starts_at
    br
    = f.datetime_select :starts_at
  
  .field
    = f.label :ends_at
    br
    = f.datetime_select :ends_at
  
  .field
    = f.label :source
    br
    = f.text_field :source
  
  .actions
    = f.submit

app/views/events/edit.html.slim
h1 Editing event

= render 'form'

= link_to 'Show', @event
|  | 
= link_to 'Back', events_path

app/views/events/index.html.slim
h1 Listing events

table
  tr
    th Title
    th Description
    th Starts
    th Ends
    th Source
    th Category
    th
    th
    th

  - @events.each do |event|
    tr
      td = event.title
      td = event.description
      td = I18n.l(event.starts_at, :format => :short)
      td = I18n.l(event.ends_at, :format => :short)
      td = event.source
      td = event.category.name
      td = link_to 'Show', event
      td = link_to 'Edit', edit_event_path(event)
      td = link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete

br

= link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p
  b Title: 
  = @event.title

p
  b Description: 
  = @event.description

p
  b Category: 
  = @event.category.name

p
  b Published on: 
  = I18n.l(@event.created_at, :format => :short)

p
  b Starts at: 
  = @event.starts_at

p
  b Ends at: 
  = @event.ends_at

p
  b Source: 
  = @event.source

= link_to 'Edit', edit_event_path(@event)
|  | 
= link_to 'Back', events_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Semaphore
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .container
      = yield